theme = "hugo-theme-codex" 

title = "Josh's Personal Website"
languageCode = "en-us"
baseURL = "https://example.org/"
copyright = "Â© 2022"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  github = "https://github.com/JoshHumpherey"
  email = "mailto:jhumphrey321@gmail.com"
  linkedin = "https://www.linkedin.com/in/josh-humphrey-ba4369100/"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub", "LinkedIn", "Email"]

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "bitcoin"
  name = "bitcoin"
  title = "Bitcoin"
  url = "/bitcoin"

[[menu.main]]
  identifier = "books"
  name = "books"
  title = "Books"
  url = "/books"



